### ISSUE TITLE
Complete Community Checklist

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#227]
### What's your idea?

On [/community](https://github.com/EthanThatOneKid/acmcsuf.com/community), there is a checklist to help with creating a good community experience on our GitHub repository.

- [x] Add repository description
- [x] Add README.md
- [x] Add Code of Conduct (#203)
- [x] Add CONTRIBUTING.md
- [x] Add LICENSE.md (#230)
- [x] Add Issue Templates
- [x] Add Pull Request Templates (#231)

### Related

- Recommended community standards: <https://opensource.guide/>
