### ISSUE TITLE
Events: <EventItem /> enhancements tracker

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#310]
#### Actionbar Enhancement

- [x] <https://github.com/EthanThatOneKid/acmcsuf.com/issues/281>
- [x] #312
- [x] #317
- [x] #327

#### Related Bugs/Enhancements

- [x] <https://github.com/EthanThatOneKid/acmcsuf.com/issues/309>
- [x] <https://github.com/EthanThatOneKid/acmcsuf.com/issues/313>
- [x] #330
- [x] #334
- [x] #346 
- [x] #422

#### Future enhancements

- [ ] #181
- [x] #339

**Comment by EthanThatOneKid** [comment]
This umbrella has been ready to resolve since [v3.0](https://github.com/EthanThatOneKid/acmcsuf.com/releases/tag/v3.0).
