### ISSUE TITLE
Netlify: Migrate from Vercel to Netlify

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#697]
### What's your idea?

https://docs.netlify.com/welcome/add-new-site/

- [x] Transfer environment variables from [Vercel](https://vercel.com/ethanthatonekid/acm-csuf-site/settings/environment-variables) to [Netlify](https://app.netlify.com/sites/acmcsuf/settings/env).
- [ ] Set up [Netlify Deploy Previews](https://docs.netlify.com/site-deploys/deploy-previews/).
- [ ] Set up `acmcsuf.com` domain configuration ([Configure external DNS for a custom domain](https://docs.netlify.com/domains-https/custom-domains/configure-external-dns/)).
- [x] Replace [Vercel Analytics](https://github.com/EthanThatOneKid/acmcsuf.com/blob/7e328c6cd9606fc394b3f0e3c0072550ad72849b/src/lib/public/analytics/vitals.ts#L28) ([current implementation](https://github.com/EthanThatOneKid/acmcsuf.com/blob/7e328c6cd9606fc394b3f0e3c0072550ad72849b/src/routes/+layout.svelte#L10)) with [Netlify Analytics](https://docs.netlify.com/monitor-sites/analytics/) ([Lighthouse](https://docs.netlify.com/monitor-sites/lighthouse/), [related](https://github.com/EthanThatOneKid/acmcsuf.com/blob/7e328c6cd9606fc394b3f0e3c0072550ad72849b/svelte.config.js#L12-L13)).
- [x] Update [.env.example](https://github.com/EthanThatOneKid/acmcsuf.com/blob/7e328c6cd9606fc394b3f0e3c0072550ad72849b/.env.example#L6).
- [ ] Update documentation ([README.md](https://github.com/EthanThatOneKid/acmcsuf.com/blob/7e328c6cd9606fc394b3f0e3c0072550ad72849b/README.md?plain=1#L21) and [GETTING_STARTED.md](https://github.com/EthanThatOneKid/acmcsuf.com/blob/7e328c6cd9606fc394b3f0e3c0072550ad72849b/GETTING_STARTED.md?plain=1#L7)).
