### ISSUE TITLE
The Fall 2022-Spring 2023 redesign

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#714]
### What's your idea?

Our design team has **HUGE** design changes in store for the future of our club website.

### Plan

- [ ] Update branding on the repository
  - [ ] Update [issue template banners](https://raw.githubusercontent.com/EthanThatOneKid/acmcsuf.com/main/.github/ISSUE_TEMPLATE)
- [ ] Implement updated designs of all existing pages
  - [ ] Fall 2022-Spring 2023 Redesign: Index page
  - [ ] ...issues to be created...
